### ISSUE TITLE
multithreading in the future?

### ISSUE THREAD

**Issue by FrankReh** [triblesspace/tribles-rust#3]
1.
I see Arc is being used to share keys.

Do you want to support a multi-threaded environment done the road with this library? If not, one of us could change it to use Rc instead.

If you do want to support multi-threaded, the mutable globals that work the alternate hashing algorithm might have to be reworked a little. Maybe they shouldn't be global, and the functions that are global now would become methods to some triple_tree instance or something.

2.
The ByteEntry trait doesn't appear to serve a purpose now that the design uses a single node type that is a union.
Which way did you see the design going? The single union route, like C, but a few unsafe wrappers where the actual type has to be accessed, or an enumerated type, where the fact that each variant would support the ByteEntry trait would still be useful to track?

If the ByteEntry trait is old and not needed, the ByteBucket struct (which is an array of `ByteEntry`s) could become an array of Head (the union).

**Comment by somethingelseentirely** [comment]
Yeah multithreading is definitely planned. The persistent/copy-on-write data-structure is not the fastest single threaded, but kinda offsets that with extremely cheap set operations defined over it. So it's quite natural to do operations on a common ancestor in parallel and then just merge the results.

Could you elaborate what your concerns are?
I'm aware that the global [`RAND`](https://github.com/triblesspace/tribles-rust/blob/master/src/bytetable.rs#L18) is racy, but since it's just a pseudorandom value, it shouldn't be an issue. Since the other globals are only ever written once I assumed that protecting them with `Once` would be sufficient, but my UB foo is not the strongest 😉 

---

The `ByteEntry` is used as a marker trait to guarantee that the things stored in the table uphold the property that they are zeroable (equivalent to the [bytemuck trait](https://docs.rs/bytemuck/latest/bytemuck/trait.Zeroable.html)), with the addition that the value corresponding to all zeroes must also return `None` for `key()`.

The reason behind is that it allows us to treat a zero initialised block of memory as an empty hash-table, without any additional initialisation costs.

I agree that that's probably a bit overkill for something that's just used internally, but we planned on pulling out the bytetable into a separate crate in the future.

---

As for going the union or enum route. We've had several unsuccessful attempts to rewrite everything to safe enums 😅, sadly they don't provide enough control over memory layout and padding and without first class variant types there is no way to implement traits for them. So one has to choose between loosing a tight memory layout or having to wrangle unmaintainable functions. So I'm pretty certain that we'll stick with unions, at least until the language changes/enhances how enums work.

**Comment by somethingelseentirely** [comment]
A lot of things have changed so this might not be relevant anymore.
